<<<<<<< HEAD
	ALTER TABLE Trips
	ALTER COLUMN VendorID VARCHAR(1000)

	ALTER TABLE Trips
	ALTER COLUMN
	lpep_pickup_datetime VARCHAR(1000)

	ALTER TABLE Trips
	ALTER COLUMN lpep_dropoff_datetime VARCHAR(1000)

	ALTER TABLE Trips
	ALTER COLUMN store_and_fwd_flag VARCHAR(1000)

	ALTER TABLE Trips
	ALTER COLUMN RatecodeID  VARCHAR(1000)

	ALTER TABLE Trips
	ALTER COLUMN PULocationID  VARCHAR(1000)

	ALTER TABLE Trips
	ALTER COLUMN DOLocationID  VARCHAR(1000)

	ALTER TABLE Trips
	ALTER COLUMN passenger_count  VARCHAR(1000)

	ALTER TABLE Trips
	ALTER COLUMN trip_distance VARCHAR(1000)

	ALTER TABLE Trips
	ALTER COLUMN fare_amount VARCHAR(1000)

	ALTER TABLE Trips
	ALTER COLUMN extra VARCHAR(1000)

	ALTER TABLE Trips
	ALTER COLUMN mta_tax VARCHAR(1000)

	ALTER TABLE Trips
	ALTER COLUMN tip_amount VARCHAR(1000)

	ALTER TABLE Trips
	ALTER COLUMN
	tolls_amount VARCHAR(1000)

	ALTER TABLE Trips
	ALTER COLUMN
	improvement_surcharge VARCHAR(1000)

	ALTER TABLE Trips
	ALTER COLUMN
	total_amount VARCHAR(1000)

	ALTER TABLE Trips
	ALTER COLUMN
	payment_type  VARCHAR(1000)

	ALTER TABLE Trips
	ALTER COLUMN
	trip_type  VARCHAR(1000)

	ALTER TABLE Trips
	ALTER COLUMN
=======
	ALTER TABLE Trips
	ALTER COLUMN VendorID VARCHAR(1000)

	ALTER TABLE Trips
	ALTER COLUMN
	lpep_pickup_datetime VARCHAR(1000)

	ALTER TABLE Trips
	ALTER COLUMN lpep_dropoff_datetime VARCHAR(1000)

	ALTER TABLE Trips
	ALTER COLUMN store_and_fwd_flag VARCHAR(1000)

	ALTER TABLE Trips
	ALTER COLUMN RatecodeID  VARCHAR(1000)

	ALTER TABLE Trips
	ALTER COLUMN PULocationID  VARCHAR(1000)

	ALTER TABLE Trips
	ALTER COLUMN DOLocationID  VARCHAR(1000)

	ALTER TABLE Trips
	ALTER COLUMN passenger_count  VARCHAR(1000)

	ALTER TABLE Trips
	ALTER COLUMN trip_distance VARCHAR(1000)

	ALTER TABLE Trips
	ALTER COLUMN fare_amount VARCHAR(1000)

	ALTER TABLE Trips
	ALTER COLUMN extra VARCHAR(1000)

	ALTER TABLE Trips
	ALTER COLUMN mta_tax VARCHAR(1000)

	ALTER TABLE Trips
	ALTER COLUMN tip_amount VARCHAR(1000)

	ALTER TABLE Trips
	ALTER COLUMN
	tolls_amount VARCHAR(1000)

	ALTER TABLE Trips
	ALTER COLUMN
	improvement_surcharge VARCHAR(1000)

	ALTER TABLE Trips
	ALTER COLUMN
	total_amount VARCHAR(1000)

	ALTER TABLE Trips
	ALTER COLUMN
	payment_type  VARCHAR(1000)

	ALTER TABLE Trips
	ALTER COLUMN
	trip_type  VARCHAR(1000)

	ALTER TABLE Trips
	ALTER COLUMN
>>>>>>> 32f823f99654fa91c1c314a9f6d58fc9fb7f7e6d
	congestion_surcharge VARCHAR(1000)